version: "3.7"
services:
  postgres:
    image: debezium/postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=rbac-service
      - PG_DATA=/data
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
    volumes:
      - type: volume
        source: postgres-volume-data
        target: /data

volumes:
  postgres-volume-data:
